vsg: print file name when ClassifyError
In current implementation the user see something like the following when
ClassifyError is raised:

    Error: Unexpected token detected while parsing procedure_call_statement @ Line 49, Column 22 in file None
           Expecting : ;
           Found     : )

In a project that contains multiple files, the user is clueless as he does not
know which of the files caused the error.

This change adds the name of the file to the message.

    Error while processing xxx:
    Error: Unexpected token detected while parsing procedure_call_statement @ Line 49, Column 22 in file None
           Expecting : ;
           Found     : )

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>